title: Hiatt Zhao
author: Hiatt Zhao
email: hiattzhao@gmail.com
description: > # this means to ignore newlines
  Portfolio

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
#  - blog.md
  - photo.md
  - code.md
  - travel.md
  - books.md
  - connect.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag

disqus:
  shortname: hiattzhao
